### ISSUE TITLE
Order preserving constraint 

### ISSUE THREAD

**Issue by lxianwei003** [guillermo-navas-palencia/clogistic#2]
Can this package achieve Order preserving constraint weight constraints in Logistic Regression ? weight  satisfy a1 >= a2 >= a3 ……

**Comment by guillermo-navas-palencia** [comment]
Yes, it can. You need to create the matrix of constraints using ``scipy.optimize.LinearConstraint`` and use  ``solver="ecos"``. Example: https://github.com/guillermo-navas-palencia/clogistic#elastic-net-with-bounds-and-constraints.

Let me know if you need further assistance. Happy to help.

**Comment by lxianwei003** [comment]
Can we communicate with you by email? I have sent you an email about the problem  thank you！

**Comment by lxianwei003** [comment]
> Yes, it can. You need to create the matrix of constraints using `scipy.optimize.LinearConstraint` and use `solver="ecos"`. Example: https://github.com/guillermo-navas-palencia/clogistic#elastic-net-with-bounds-and-constraints.
> 
> Let me know if you need further assistance. Happy to help.



> Yes, it can. You need to create the matrix of constraints using `scipy.optimize.LinearConstraint` and use `solver="ecos"`. Example: https://github.com/guillermo-navas-palencia/clogistic#elastic-net-with-bounds-and-constraints.
> 
> Let me know if you need further assistance. Happy to help.

Can we communicate with you by email? I have sent you an email about the problem thank you！

**Comment by guillermo-navas-palencia** [comment]
I close this issue since it was already solved via email.
