### ISSUE TITLE
How to generalize to GLM model

### ISSUE THREAD

**Issue by ZAn-next** [guillermo-navas-palencia/clogistic#4]
Hi 
I find this package is quite helpful in LR; I am also modeling using Poisson distribution. how hard is it to extend to any GLM model?

**Comment by guillermo-navas-palencia** [comment]
Hi @ZAn-next.

Interesting, thanks for your proposal. It should not take much effort given the similarities with Logistic regression. However, this package is focused on Logistic regression, and other target domains different from Bernoulli are not considered. The scikit-learn library has this functionality in case you are interested: https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models
